// packages/ui/src/lib/Textarea.svelte
<script lang="ts">
  import { cx } from "./cx.js";

  interface Props {
    value?: string;
    rows?: number;
    invalid?: boolean;
    disabled?: boolean;
    class?: string;
    [key: string]: unknown;
  }

  let {
    value = $bindable(""),
    rows = 4,
    invalid = false,
    disabled = false,
    class: className = "",
    ...rest
  }: Props = $props();

  const cls = $derived(
    cx(
      "w-full min-h-24 px-4 py-3 rounded-lg bg-input text-foreground border border-border placeholder:text-muted-foreground transition-colors duration-200 resize-y focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:opacity-50 disabled:cursor-not-allowed",
      invalid && "border-destructive ring-destructive",
      className,
    ),
  );
</script>

<textarea
  bind:value
  {rows}
  {disabled}
  class={cls}
  aria-invalid={invalid || undefined}
  data-slot="textarea"
  {...rest}
></textarea>

// packages/bundu-ui/src/ui/textarea.tsx
import * as React from "react";

import { cn } from "../lib/utils";

/**
 * Textarea — native <textarea> styled to the Nyuchi Design System
 * tokens (shadcn pattern over the Five-African-Minerals tokens).
 * Dependency-free and SSR-friendly. Forwards every standard textarea
 * prop (name, id, placeholder, required, rows, value, defaultValue, …)
 * via `...props`.
 */
export const textareaClasses =
  "flex min-h-24 w-full rounded-lg border border-border bg-background px-4 py-3 text-body text-foreground transition-colors placeholder:text-muted-foreground outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:opacity-50 disabled:cursor-not-allowed";

export interface TextareaProps
  extends React.TextareaHTMLAttributes<HTMLTextAreaElement> {
  /** Astro-style class attribute (merged with `className`). */
  class?: string;
  className?: string;
}

export function Textarea({
  class: astroClass,
  className,
  ...props
}: TextareaProps) {
  return (
    <textarea
      data-slot="textarea"
      className={cn(textareaClasses, astroClass, className)}
      {...props}
    />
  );
}
