// packages/bundu-ui/src/ui/tooltip.tsx
"use client";

import * as React from "react";

import { cn } from "../lib/utils";

/**
 * Tooltip — a minimal accessible tooltip.
 *
 * Deliberately NOT Radix (kept dependency-light): wraps a single
 * trigger and shows `content` on hover AND keyboard focus (so it's not
 * hover-only), wiring `aria-describedby` to the tooltip's generated id
 * and `role="tooltip"`. Escape dismisses it. Positioning is CSS-only
 * (absolute, `side` prop) — no floating-ui. Colours come from the
 * semantic `foreground` / `background` tokens — no hex.
 *
 * The trigger must be a single focusable element (button/link). The
 * wrapper is an inline span so it doesn't disturb layout.
 */
export interface TooltipProps {
  /** Tooltip text (or rich node) shown on hover/focus. */
  content: React.ReactNode;
  side?: "top" | "bottom" | "left" | "right";
  class?: string;
  className?: string;
  children: React.ReactNode;
}

const sideClasses: Record<NonNullable<TooltipProps["side"]>, string> = {
  top: "bottom-full left-1/2 -translate-x-1/2 mb-2",
  bottom: "top-full left-1/2 -translate-x-1/2 mt-2",
  left: "right-full top-1/2 -translate-y-1/2 mr-2",
  right: "left-full top-1/2 -translate-y-1/2 ml-2",
};

export function Tooltip({
  content,
  side = "top",
  class: astroClass,
  className,
  children,
}: TooltipProps) {
  const [open, setOpen] = React.useState(false);
  const id = React.useId();

  return (
    <span
      className="relative inline-flex"
      data-slot="tooltip"
      onMouseEnter={() => setOpen(true)}
      onMouseLeave={() => setOpen(false)}
      onFocusCapture={() => setOpen(true)}
      onBlurCapture={() => setOpen(false)}
      onKeyDown={(e) => {
        if (e.key === "Escape") setOpen(false);
      }}
    >
      <span aria-describedby={open ? id : undefined} className="inline-flex">
        {children}
      </span>
      <span
        role="tooltip"
        id={id}
        hidden={!open}
        data-slot="tooltip-content"
        data-state={open ? "open" : "closed"}
        className={cn(
          "pointer-events-none absolute z-50 w-max max-w-xs rounded-md bg-foreground px-2.5 py-1.5 text-caption font-medium text-background shadow-md",
          sideClasses[side],
          astroClass,
          className,
        )}
      >
        {content}
      </span>
    </span>
  );
}

// packages/ui/src/lib/Tooltip.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { cx } from "./cx.js";

  type Side = "top" | "bottom" | "left" | "right";

  interface Props {
    /** Tooltip text content. */
    text: string;
    side?: Side;
    class?: string;
    /** The trigger element(s). */
    children?: Snippet;
    [key: string]: unknown;
  }

  let {
    text,
    side = "top",
    class: className = "",
    children,
    ...rest
  }: Props = $props();

  let open = $state(false);
  const id = `tt-${Math.random().toString(36).slice(2, 8)}`;

  const sides: Record<Side, string> = {
    top: "bottom-full left-1/2 -translate-x-1/2 mb-2",
    bottom: "top-full left-1/2 -translate-x-1/2 mt-2",
    left: "right-full top-1/2 -translate-y-1/2 mr-2",
    right: "left-full top-1/2 -translate-y-1/2 ml-2",
  };

  function show() {
    open = true;
  }
  function hide() {
    open = false;
  }
  function onKeydown(e: KeyboardEvent) {
    if (e.key === "Escape") hide();
  }
</script>

<span
  class={cx("relative inline-flex", className)}
  data-slot="tooltip"
  onmouseenter={show}
  onmouseleave={hide}
  onfocusin={show}
  onfocusout={hide}
  onkeydown={onKeydown}
  aria-describedby={open ? id : undefined}
  {...rest}
>
  {@render children?.()}
  <span
    {id}
    role="tooltip"
    class={cx(
      "pointer-events-none absolute z-50 w-max max-w-xs rounded-md bg-foreground px-2.5 py-1.5 text-caption font-medium text-background shadow-md transition-opacity duration-150",
      sides[side],
      open ? "opacity-100" : "opacity-0",
    )}
    aria-hidden={!open}
  >
    {text}
  </span>
</span>
